typedef struct _PCI_VENTABLE
{
	unsigned short VenId ;
	char *VenShort ;
	char *VenFull ;
	char *Web;
}  PCI_VENTABLE, *PPCI_VENTABLE ;

PCI_VENTABLE PciVenTable [] =
{
		{ 0x0000, "Unknown", "This vendor is unknown" },
		{ 0x001A, "Ascend", "Ascend Communications Inc.", "*" } , 
		{ 0x0033, "Paradyne", "Paradyne Corporation", "*" },
		{ 0x003D, "Real 3D", "Real 3D Inc. Graphics", "*" },
		{ 0x0070, "Hauppauge" , "Hauppauge Computer Works Inc.", "*" },
		{ 0x0E11, "Compaq", "Compaq Computer Corporation", "*" } ,	
	
/* */	{ 0x1000, "Symbios", "Symbios Logic Inc./NCR", "*" } ,
		{ 0x1002, "ATI", "ATI Technologies", "www.atitech.ca" } ,
		{ 0x1003, "ULSI", "ULSI Systems" } , 
		{ 0x1004, "VLSI", "VLSI Technology Inc.", "*" } ,
/* */	{ 0x1005, "Avance", "Avance Logic Inc.", "www.realtek.com.tw/cp/cp.html" } ,
/* */	{ 0x1006, "Reply", "Reply Group" } ,
/* */	{ 0x1007, "NetFRAME", "NetFRAME Systems Inc.", "*" } ,
/* */	{ 0x1008, "Epson", "Seiko Epson Corporation", "*" } ,
		{ 0x100A, "Phoenix", "Phoenix Technologies Ltd.", "*" } ,
		{ 0x100B, "National", "National Semiconductor Corporation", "*" } ,
		{ 0x100C, "Tseng", "Tseng Labs Inc.", "*" } ,
/* */	{ 0x100D, "AST", "AST Computer", "*" } ,
/* */	{ 0x100E, "Weitek", "Weitek Corporation" } ,	
	
		{ 0x1010, "VideoLogic", "VideoLogic Ltd.", "*" } ,
		{ 0x1011, "Digital", "Digital Equipment Corporation/Compaq", "*" } ,
		{ 0x1012, "Micronics", "Micronics Computers Inc.", "*" } ,
		{ 0x1013, "Cirrus", "Cirrus Logic Inc.", "*" } ,
		{ 0x1014, "IBM", "IBM Corporation", "*" } ,
/* */	{ 0x1015, "LSI Logic", "LSI Logic Canada" } ,
		{ 0x1016, "Fujitsu", "Fujitsu ICL", "*" },
		{ 0x1017, "Spea", "Spea Software AG", "www.diamondmm.de" } ,
		{ 0x1018, "Unisys", "Unisys Corporation", "*" } ,
/* */	{ 0x1019, "ECS", "EliteGroup Computer Systems", "www.ecs.com.tw" } ,
		{ 0x101A, "NCR", "NCR Corporation/AT&T", "*" } ,
/* */	{ 0x101B, "Vitesse", "Vitesse Semiconductor", "*" } ,
/* */	{ 0x101C, "WD", "Western Digital Corporation", "www.westerndigital.com" } ,
		{ 0x101E, "AMI", "American Megatrends Inc.", "*" } ,
/* */	{ 0x101F, "PictureTel", "PictureTel Corporation", "*" } ,

		{ 0x1020, "Hitachi", "Hitachi Computer Electronics", "*" } ,
		{ 0x1021, "OKI", "Oki Electric Industry Company Ltd.", "*" } ,
		{ 0x1022, "AMD", "Advanced Micro Devices", "*" } ,
		{ 0x1023, "Trident", "Trident Microsystems", "*" } ,
/* */	{ 0x1024, "ZDS", "Zenith Data Systems", "*" } ,
		{ 0x1025, "Acer", "Acer Inc.", "*" } ,
		{ 0x1028, "Dell", "Dell Computer Corporation", "*" } ,
/* */	{ 0x1029, "Siem-Nix", "Siemens Nixdorf AG", "www.siemens.de" } ,
		{ 0x102A, "LSIL", "LSI Logic Corporation", "*" } ,
		{ 0x102B, "Matrox", "Matrox Graphics Inc.", "*" } ,
		{ 0x102C, "Chips", "Chips and Technologies Inc./Intel", "www.intel.com" } ,
/* */	{ 0x102D, "Wyse", "Wyse Technology Inc.", "*" } ,
		{ 0x102E, "Olivetti", "Olivetti Advanced Technology", "www.atc.olivetti.com" } ,
/* */	{ 0x102F, "Toshiba", "Toshiba America", "*" } ,
	
/* */	{ 0x1030, "TMC", "TMC Research" } ,
/* */	{ 0x1031, "miro", "miro Computer Products AG", "www.miro.de" } ,
  		{ 0x1032, "Compaq", "Compaq Corporation", "*" } , 
		{ 0x1033, "NEC", "NEC Corporation", "*" } ,
/* */	{ 0x1034, "Burndy", "Burndy Corporation" } ,
/* */	{ 0x1035, "C&CRL", "Computer & Communication Research Lab" } ,
/* */	{ 0x1036, "FDomain", "Future Domain", "www.adaptec.com" } ,
		{ 0x1037, "Hitachi", "Hitachi Micro Systems Inc.", "*" } ,
		{ 0x1038, "AMP", "AMP Inc.", "*" } ,
		{ 0x1039, "SIS", "Silicon Integrated Systems", "www.sis.com.tw" } ,
/* */	{ 0x103A, "Seiko", "Seiko Epson Corporation", "www.epson.co.jp" } ,
/* */	{ 0x103B, "Tatung", "Tatung Corporation Of America", "www.tatungusa.com" } ,
		{ 0x103C, "HP", "Hewlett-Packard Company", "*" } ,
/* */	{ 0x103E, "Solliday", "Solliday Engineering Inc.", "www.secorp.com" } ,
		{ 0x103F, "Logic Mod.", "Synopsys/Logic Modeling Group", "www.synopsys.com" } ,
	
/* */	{ 0x1040, "Kubota", "Kubota Pacific Computer Inc." } ,
/* */	{ 0x1041, "Computrend", "Computrend" } ,
		{ 0x1042, "Micron", "Micron Technology Inc.", "*" } ,
/* */	{ 0x1043, "ASUSTek", "ASUSTek Computers Inc.", "www.asus.com" } ,
		{ 0x1044, "DPT", "Distributed Processing Technology", "*" } ,
		{ 0x1045, "OPTi", "OPTi Inc.", "*" } ,
/* */	{ 0x1046, "IPC", "IPC Corporation Ltd." } ,
/* */	{ 0x1047, "Genoa", "Genoa Electronics Corporation", "www.genoasys.com" } ,
		{ 0x1048, "ELSA", "ELSA AG", "www.elsa.de" } ,
		{ 0x1049, "Fountain", "Fountain Technologies Inc." } ,
/* */	{ 0x104A, "SGS", "SGS Thomson Microelectric", "www.st.com" } ,
/* */	{ 0x104B, "Buslogic", "Buslogic/Mylex Corporation", "*" } ,
		{ 0x104C, "TI", "Texas Instruments Inc.", "*" } ,
		{ 0x104D, "Sony", "Sony Corporation", "*" } ,
		{ 0x104E, "Oak", "Oak Technology Inc.", "www.oaktech.com" } ,
/* */	{ 0x104F, "Co-Time", "Co-Time Computer Ltd." } ,
	
		{ 0x1050, "Winbond", "Winbond Electronics Corporation", "www.winbond.com.tw" } ,
/* */	{ 0x1051, "Anigma", "Anigma Corporation" } , // Continue
/* */	{ 0x1052, "Young", "Young Micro Systems" } ,
		{ 0x1054, "Hitachi", "Hitachi Ltd." , "*" } ,
		{ 0x1055, "StdMicro", "Standard Microsystems Corporation" , "www.smsc.com" } ,
/* */	{ 0x1056, "ICL", "ICL", "*" } ,
		{ 0x1057, "Motorola", "Motorola", "www.mot.com" } ,
		{ 0x1058, "ETRI", "Electronics & Teleccommunication Research" } ,
		{ 0x1059, "Teknor", "Teknor Industrial Computers Inc." , "*" } ,
/* */	{ 0x105A, "Promise", "Promise Technology", "*" } ,
		{ 0x105B, "Foxconn", "Foxconn International Inc." } ,
/* */	{ 0x105C, "Wipro", "Wipro Infotech Limited" } ,
		{ 0x105D, "Number9", "Number Nine Visual Technology", "www.nine.com" } ,
		{ 0x105E, "Vtech", "Vtech Engineering Canada Ltd.", "*" } ,
		{ 0x105F, "Infotronic", "Infotronic America Inc." } ,
	
/* */	{ 0x1060, "UMC", "United Microelectronics Corporation", "www.umc.com.tw" } ,
/* */	{ 0x1061, "8x8", "8x8 Inc./X Tech", "*" } ,
/* */	{ 0x1062, "Maspar", "Maspar Computer Corporation" } ,
		{ 0x1063, "OOA", "Ocean Office Automation" } ,
		{ 0x1064, "Alcatel", "Alcatel Cit", "*" } ,
/* */	{ 0x1065, "TM", "Texas Microsystems" } ,
/* */	{ 0x1066, "Picopower", "Picopower Technology" } ,
		{ 0x1067, "Mitsubishi", "Mitsubishi Electric America" } ,
		{ 0x1068, "Div. Tech.", "Diversified Technology" } ,
		{ 0x1069, "Mylex", "Mylex Corporation", "*" } ,
/* */	{ 0x106A, "Aten", "Aten Research Inc." } ,
		{ 0x106B, "Apple", "Apple Computer Inc.", "*" } ,
/* */	{ 0x106C, "Hyundai", "Hyundai Electronics America" } ,
		{ 0x106D, "Sequent", "Sequent Computer Systems", "*" } ,
/* */	{ 0x106E, "DFI", "DFI Inc." } ,
/* */	{ 0x106F, "CityGate", "City Gate Development Ltd." } ,
	
		{ 0x1070, "Daewoo", "Daewoo Telecom Ltd." } ,
/* */	{ 0x1071, "Mitac", "Mitac", "*" } ,
/* */	{ 0x1072, "GIT", "GIT Company Ltd." } ,
		{ 0x1073, "Yamaha", "Yamaha Corporation", "*" } ,
/* */	{ 0x1074, "Nexgen", "Nexgen Microsysteme" } ,
/* */	{ 0x1075, "AIR", "Advanced Integration Research" } ,
/* */	{ 0x1076, "Chaintech", "Chaintech Computer Company Ltd." } ,
		{ 0x1077, "QLogic", "QLogic" } ,
		{ 0x1078, "Cyrix", "Cyrix Corporation", "*" } ,
		{ 0x1079, "IBus", "I-Bus", "*" } ,
/* */	{ 0x107A, "Networth", "Networth" } ,
		{ 0x107B, "Gateway", "Gateway 2000 Inc.", "*" } ,
/* */	{ 0x107C, "Goldstar", "Goldstar Company Ltd.", "www.lgeus.com" } ,
/* */	{ 0x107D, "Leadtek", "Leadtek Research Inc.", "*" } ,
		{ 0x107E, "Interphase", "Interphase Corporation" } ,
/* */	{ 0x107F, "DTC", "Data Technology Corporation" } ,
	
/* */	{ 0x1080, "Contaq", "Contaq Microsystems" } ,
/* */	{ 0x1081, "Supermac", "Supermac Technology Inc." } ,
/* */	{ 0x1082, "EFA", "EFA Corporation Of America" } ,
/* */	{ 0x1083, "Forex", "Forex Computer Corporation" } ,
/* */	{ 0x1084, "Parador", "Parador" } ,
		{ 0x1085, "Tulip", "Tulip Computers International B.V.", "*" } ,
/* */	{ 0x1086, "JBond", "J. Bond Computer Systems", "*" } ,
/* */	{ 0x1087, "Cache", "Cache Computer" } ,
/* */	{ 0x1088, "MS Son", "Microcomputer Systems M Son" } ,
		{ 0x1089, "DG", "Data General Corporation", "*" } ,
		{ 0x108A, "Bit3", "SBS Bit 3 Operations", "*" } ,
/* */	{ 0x108C, "Elonex", "Elonex PLC c/o Oakleigh Systems Inc." } ,
		{ 0x108D, "Olicom", "Olicom Inc.", "*" } ,
		{ 0x108E, "Sun", "Sun Microsystems Computer Corporation", "*" } ,
		{ 0x108F, "Systemsoft", "Systemsoft Corporation", "*" } ,
	
		{ 0x1090, "Encore", "Encore Computer Corporation", "*" } ,
		{ 0x1091, "Intergraph", "Intergraph Corporation" } ,
		{ 0x1092, "Diamond", "Diamond Multimedia Systems", "www.diamondmm.com" } ,
		{ 0x1093, "Nat. Inst.", "National Instruments" } ,
/* */	{ 0x1094, "FIC", "First Int'l Computers" } ,
		{ 0x1095, "CMD", "CMD Technology Inc.", "*" } ,
		{ 0x1096, "Alacron", "Alacron Inc.", "*" } ,
		{ 0x1097, "Appian", "Appian/ETMA Graphics" } ,
/* */	{ 0x1098, "Quantum", "Quantum Designs Ltd." } ,
/* */	{ 0x1099, "Samsung", "Samsung Electronics Company Ltd.", "*" } ,
/* */	{ 0x109A, "PackardBell", "Packard Bell NEC Inc.", "*" } ,
/* */	{ 0x109B, "Gemlight", "Gemlight Computer Company", "*" } ,
/* */	{ 0x109C, "Megachips", "Megachips Corporation" } ,
/* */	{ 0x109D, "Zida", "Zida Technologies Ltd.", "*" } ,
		{ 0x109E, "Brooktree", "Brooktree Corporation/Conexant", "www.conexant.com" } ,
/* */	{ 0x109F, "Trigem", "Trigem Computer Inc.", "*" } ,
	
		{ 0x10A0, "Meidensha", "Meidensha Corporation" } ,
/* */	{ 0x10A1, "Juko", "Juko Electronics Inc. Ltd." } ,
		{ 0x10A2, "Quantum", "Quantum Corporation", "*" } ,
/* */	{ 0x10A3, "Everex", "Everex Systems Inc." } ,
/* */	{ 0x10A4, "Globe", "Globe Manufacturing Sales" } ,
/* */	{ 0x10A5, "Racal", "Racal Interlan", "*" } ,
/* */	{ 0x10A6, "Informtech", "Informtech Industrial Ltd." } ,
/* */	{ 0x10A7, "Benchmarq", "Benchmarq Microelectronics" } ,
/* */	{ 0x10A8, "Sierra", "Sierra Semiconductor" } ,
		{ 0x10A9, "SGI", "Silicon Graphics Inc.", "*" } ,
		{ 0x10AA, "Auctor", "Auctor Corporation" } ,
/* */	{ 0x10AB, "Digicom", "Digicom" } ,
		{ 0x10AC, "Honeywell", "Honeywell IAC" } ,
/* */	{ 0x10AD, "Symphony", "Symphony Labs" } ,
/* */	{ 0x10AE, "Cornerstone", "Cornerstone Technology" } ,
		{ 0x10AF, "MCS", "Micro Computer Systems Inc." } ,
	
		{ 0x10B0, "Cardexpert", "Cardexpert Technology" } ,
/* */	{ 0x10B1, "Cabletron", "Cabletron Systems Inc.", "*" } ,
/* */	{ 0x10B2, "Raytheon", "Raytheon Company", "*" } ,
/* */	{ 0x10B3, "Databook", "Databook Inc." } ,
		{ 0x10B4, "STB", "STB Systems Inc.", "*" } ,
		{ 0x10B5, "PLX", "PLX Technology Inc." } ,
		{ 0x10B6, "Madge", "Madge Networks", "*" } ,
		{ 0x10B7, "3Com", "3Com Corporation", "*" } ,
/* */	{ 0x10B8, "Standard", "Standard Microsystems" } ,
/* */	{ 0x10B9, "ALI", "Acer Labs Inc.", "*" } ,
		{ 0x10BA, "Mitsubishi", "Mitsubishi Electric Corporation" } ,
/* */	{ 0x10BB, "Dapha", "Dapha Electronics Corporation" } ,
		{ 0x10BC, "ALR", "Advanced Logic Research Inc." } ,
/* */	{ 0x10BD, "Surecom", "Surecom Technology" } ,
		{ 0x10BE, "Tseng", "Tsenglabs International Company", "*" } ,
/* */	{ 0x10BF, "MOST", "MOST Corporation" } ,
	
/* */	{ 0x10C0, "Boca", "Boca Research Inc.", "www.bocaresearch.com" } ,
/* */	{ 0x10C1, "ICM", "ICM Corporation Ltd." } ,
		{ 0x10C2, "Auspex", "Auspex Systems Inc.", "*" } ,
/* */	{ 0x10C3, "Samsung", "Samsung Semiconductors", "*" } ,
		{ 0x10C4, "Award", "Award Software International Inc.", "*" } ,
/* */	{ 0x10C5, "Xerox", "Xerox Corporation", "*" } ,
/* */	{ 0x10C6, "Rambus", "Rambus Inc.", "*" } ,
/* */	{ 0x10C7, "Media Vision", "Media Vision" } ,
		{ 0x10C8, "Neomagic", "Neomagic Corporation", "*" } ,
		{ 0x10C9, "DataExpert", "DataExpert Corporation", "*" } ,
/* */	{ 0x10CA, "Fujitsu", "Fujitsu", "*" } ,
		{ 0x10CB, "Omron", "Omron Corporation", "*" } ,
		{ 0x10CC, "Mentor", "Mentor Arc Inc." } ,
		{ 0x10CD, "AdvanSys", "Advanced System Products Inc.", "*" } ,
/* */	{ 0x10CE, "Radius", "Radius Inc.", "*" } ,
/* */	{ 0x10CF, "TTI", "Citicorp TTI" } ,
	
		{ 0x10D0, "Fujitsu", "Fujitsu Ltd.", "*" } ,
		{ 0x10D1, "Future+", "FuturePlus Systems Corporation", "www.futureplus.com" } ,
		{ 0x10D2, "Molex", "Molex Inc.", "*" } ,
/* */	{ 0x10D3, "Jabil", "Jabil Circuit Inc.", "*" } ,
/* */	{ 0x10D4, "Hualon", "Hualon Microelectronics" } ,
/* */	{ 0x10D5, "Autologic", "Autologic Inc." } ,
/* */	{ 0x10D6, "Cetia", "Cetia" } ,
/* */	{ 0x10D7, "BCM", "BCM Advanced Research" } ,
/* */	{ 0x10D8, "APL", "Advanced Peripherals Labs" } ,
/* */	{ 0x10D9, "Macronix", "Macronix International Company Ltd.", "*" } ,
/* */	{ 0x10DA, "T-C", "Thomas-Conrad Corporation" } ,
		{ 0x10DB, "Rohm", "Rohm LSI Systems Inc.", "*" } ,
/* */	{ 0x10DC, "CERN", "CERN/EPC/EDU", "www.cern.ch" } ,
		{ 0x10DD, "E&S", "Evans & Sutherland" } ,
		{ 0x10DE, "Nvidia", "Nvidia Corporation", "*" } ,
		{ 0x10DF, "Emulex", "Emulex Corporation", "*" } ,
	
		{ 0x10E0, "IXMicro", "IXMicro", "*" } ,
/* */	{ 0x10E1, "Tekram", "Tekram Technology Corporation Ltd.", "*" } ,
/* */	{ 0x10E2, "Aptix", "Aptix Corporation", "*" } ,
		{ 0x10E3, "Tundra", "Tundra Semiconductor Corporation", "*" } ,
/* */	{ 0x10E4, "Tandem", "Tandem Computers", "*" } ,
		{ 0x10E5, "MIC", "Micro Industries Corporation" } ,
/* */	{ 0x10E6, "Gainbery", "Gainbery Computer Products Inc." } ,
/* */	{ 0x10E7, "Vadem", "Vadem Inc.", "*" } ,
		{ 0x10E8, "AMCC", "Applied Micro Circuits Corporation", "*" } ,
		{ 0x10E9, "Alps", "Alps Electric Company Ltd.", "www.alpsusa.com" } ,
/* */	{ 0x10EA, "Intergraphics", "Integraphics Systems" } ,
/* */	{ 0x10EB, "Artist", "Artist Graphics" } ,
		{ 0x10EC, "Realtek", "Realtek Semiconductor Company Ltd." } ,
/* */	{ 0x10ED, "Ascii", "Ascii Corporation" } ,
		{ 0x10EE, "Xilinx", "Xilinx Inc.", "*" } ,
/* */	{ 0x10EF, "Racore", "Racore Technology Corporation", "*" } ,
	
/* */	{ 0x10F0, "Peritek", "Peritek Corporation" } ,
/* */	{ 0x10F1, "Tyan", "Tyan Computer", "*" } ,
/* */	{ 0x10F2, "Achme", "Achme Computer Inc.", "*" } ,
/* */	{ 0x10F3, "Alaris", "Alaris Inc.", "*" } ,
/* */	{ 0x10F4, "S-Mos", "S-Mos Systems" } ,
/* */	{ 0x10F5, "NKK", "NKK Corporation" } ,
/* */	{ 0x10F6, "Creative", "Creative Electronic Systems SA" } ,
		{ 0x10F7, "Matsushita", "Matsushita Electric Industrial Corporation Ltd." } ,
/* */	{ 0x10F8, "Altos", "Altos India Ltd." } ,
/* */	{ 0x10F9, "PC-Direct", "PC Direct" } ,
/* */	{ 0x10FA, "Truevision", "Truevision", "*" } ,
		{ 0x10FB, "Thesys", "Thesys Mikroelektronik MGH" } ,
		{ 0x10FC, "I-O", "I-O Data Device Inc." } ,
/* */	{ 0x10FD, "Soyo", "Soyo Computer Inc.", "*" } ,
		{ 0x10FE, "Fast", "Fast Multimedia AG" } ,
/* */	{ 0x10FF, "Ncube", "Ncube Inc.", "*" } ,
	
		{ 0x1100, "Jazz", "Jazz Multimedia" } ,
		{ 0x1101, "Initio", "Initio Corporation", "*" } ,
		{ 0x1102, "Creative", "Creative Labs", "www.creativelabs.com" } ,
/* */	{ 0x1103, "Triones", "Triones Technologies Inc." } ,
/* */	{ 0x1104, "Rasterops", "Rasterops" } ,
		{ 0x1105, "Sigma", "Sigma Designs Inc.", "www.sigmadesigns.com" } ,
		{ 0x1106, "Via", "Via Technologies Inc.", "www.viatech.com" } ,
/* */	{ 0x1107, "Stratus", "Stratus Computer Inc.", "*" } ,
/* */	{ 0x1108, "Proteon", "Proteon Inc.", "*" } ,
		{ 0x1109, "Cogent", "Cogent Data Technologies/Adaptec Inc.", "www.adaptec.com" } ,
		{ 0x110A, "Siemens", "Siemens Nixdorf AG" } ,
		{ 0x110B, "Chromatic", "Chromatic Research Inc." } ,
/* */	{ 0x110C, "Mini-Max", "Mini-Max Technology Inc." } ,
/* */	{ 0x110D, "ZNYX", "ZNYX Corporation" } ,
/* */	{ 0x110E, "CPU Tech.", "CPU Technology" } ,
/* */	{ 0x110F, "Ross", "Ross Technology" } ,
	
/* */	{ 0x1110, "Powerhouse", "Powerhouse Systems" } ,
		{ 0x1111, "SCO", "Santa Cruz Operation", "*" } ,
		{ 0x1112, "Osicom", "Osicom Technologies Inc.", "*" } ,
		{ 0x1113, "Accton", "Accton Technology Corporation", "*" } ,
/* */	{ 0x1114, "Atmel", "Atmel Corporation" } ,
/* */	{ 0x1115, "Dupont", "Dupont Pixel Systems Ltd." } ,
		{ 0x1116, "Media100", "Media 100 Inc.", "*" } ,
/* */	{ 0x1117, "Datacube", "Datacube Inc.", "*" } ,
		{ 0x1118, "Berg", "Berg Electronics" } ,
		{ 0x1119, "Vortex", "ICP-Vortex Computersysteme GmbH" } ,
		{ 0x111A, "Eff. Net.", "Efficent Networks Inc." } ,
/* */	{ 0x111B, "Teledyne", "Teledyne Electronic Systems" } ,
/* */	{ 0x111C, "Tricord", "Tricord Systems Inc.", "*" } ,
		{ 0x111D, "IDT", "Integrated Device Technology Inc." } ,
/* */	{ 0x111E, "Eldec", "Eldec Corporation", "*" } ,
/* */	{ 0x111F, "PDI", "Precision Digital Images" } ,
	
		{ 0x1120, "EMC", "EMC Corporation" } ,
/* */	{ 0x1121, "Zilog", "Zilog", "*" } ,
/* */	{ 0x1122, "MultiTech", "Multi-Tech Systems Inc.", "*" } ,
		{ 0x1123, "EDI", "Excellent Design Inc." } ,
		{ 0x1124, "Leutron", "Leutron Vision AG" } ,
/* */	{ 0x1125, "Eurocore", "Eurocore/Vigra" } ,
/* */	{ 0x1126, "Vigra", "Vigra" } ,
		{ 0x1127, "FORE", "FORE Systems Inc." } ,
/* */	{ 0x1129, "Firmworks", "Firmworks" } ,
		{ 0x112A, "Hermes", "Hermes Electronics Company Ltd." } ,
/* */	{ 0x112B, "Linotype", "Linotype - Hell AG" } ,
/* */	{ 0x112C, "Zenith", "Zenith Data Systems" } ,
/* */	{ 0x112D, "Ravicad", "Ravicad" } ,
/* */	{ 0x112E, "Infomedia", "Infomedia" } ,
		{ 0x112F, "ImagTech", "Imaging Technology Inc." } ,
	
/* */	{ 0x1130, "Computervision", "Computervision" } ,
		{ 0x1131, "Philips", "Philips Semiconductors" } ,
		{ 0x1132, "Mitel", "Mitel Corporation" } ,
		{ 0x1133, "EIC", "Eicon Technology Corporation" } ,
		{ 0x1134, "MCS", "Mercury Computer Systems Inc." } ,
/* */	{ 0x1135, "Fuji", "Fuji Xerox Co Ltd." } ,
		{ 0x1136, "Momentum", "Momentum Data Systems" } ,
/* */	{ 0x1137, "Cisco", "Cisco Systems Inc.", "*" } ,
		{ 0x1138, "Ziatech", "Ziatech Corporation", "*" } ,
		{ 0x1139, "Dyn. Pict.", "Dynamic Pictures Inc." } ,
/* */	{ 0x113A, "FWB", "FWB  Inc." } ,
/* */	{ 0x113B, "NCD", "Network Computing Devices" } ,
		{ 0x113C, "Cyclone", "Cyclone Microsystems Inc." } ,
/* */	{ 0x113D, "Leading Edge", "Leading Edge Products Inc." } ,
		{ 0x113E, "Sanyo", "Sanyo Electric Company" } ,
		{ 0x113F, "Equinox", "Equinox Systems Inc." } ,
	
/* */	{ 0x1140, "Intervoice", "Intervoice Inc." } ,
/* */	{ 0x1141, "Crest", "Crest Microsystem Inc." } ,
/* */	{ 0x1142, "Alliance", "Alliance Semiconductor", "www.alsc.com" } ,
/* */	{ 0x1143, "Netpower", "Netpower Inc." } ,
		{ 0x1144, "Vickers", "Vickers Inc. Electronic Systems" } ,
		{ 0x1145, "Workbit", "Workbit Corporation" } ,
		{ 0x1146, "Force", "Force Computers" } ,
/* */	{ 0x1147, "Interface", "Interface Corporation" } ,
		{ 0x1148, "Syskonnect", "Syskonnect" } ,
/* */	{ 0x1149, "Win System", "Win System Corporation" } ,
/* */	{ 0x114A, "VMIC", "VMIC" } ,
		{ 0x114B, "Canopus", "Canopus Company Ltd." } ,
		{ 0x114C, "Annabooks", "Annabooks" } ,
/* */	{ 0x114D, "IC Corporation", "IC Corporation" } ,
/* */	{ 0x114E, "Nikon", "Nikon Systems Inc." } ,
		{ 0x114F, "Digi", "Digi International" } ,
	
/* */	{ 0x1150, "TMC", "Thinking Machines Corporation" } ,
/* */	{ 0x1151, "JAE", "JAE Electronics Inc." } ,
/* */	{ 0x1152, "Megatek", "Megatek" } ,
/* */	{ 0x1153, "Land Win", "Land Win Electronic Corporation" } ,
		{ 0x1154, "Melco", "Melco Inc." } ,
/* */	{ 0x1155, "Pine", "Pine Technology Ltd." } ,
/* */	{ 0x1156, "Periscope", "Periscope Engineering" } ,
/* */	{ 0x1157, "Avsys", "Avsys Corporation" } ,
/* */	{ 0x1158, "Voarx", "Voarx R&D Inc." } ,
		{ 0x1159, "Mutech", "Mutech Corporation" } ,
/* */	{ 0x115A, "Harlequin", "Harlequin Ltd." } ,
/* */	{ 0x115B, "Parallax", "Parallax Graphics" } ,
		{ 0x115C, "Photron", "Photron Ltd." } ,
/* */	{ 0x115D, "Xircom", "Xircom", "*" } ,
/* */	{ 0x115E, "Peer", "Peer Protocols Inc." } ,
/* */	{ 0x115F, "Maxtor", "Maxtor Corporation" } ,
	
/* */	{ 0x1160, "Megasoft", "Megasoft Inc." } ,
/* */	{ 0x1161, "PFU", "PFU Ltd." } ,
/* */	{ 0x1162, "OA Lab", "OA Laboratory Co Ltd." } ,
		{ 0x1163, "Rendition", "Rendition Inc." } ,
		{ 0x1164, "APT", "Advanced Peripherals Technology" } ,
		{ 0x1165, "Imagraph", "Imagraph Corporation" } ,
		{ 0x1166, "Relience", "Relience Computer" } ,
/* */	{ 0x1167, "Mutoh", "Mutoh Industries Inc." } ,
/* */	{ 0x1168, "Thine", "Thine Electronics Inc." } ,
/* */	{ 0x1169, "CDAC", "Centre f/Dev. of Adv. Computing" } ,
/* */	{ 0x116A, "Polaris", "Polaris Communications" } ,
/* */	{ 0x116B, "Connectware", "Connectware Inc." } ,
/* */	{ 0x116C, "Int Res.", "Intelligent Resources" } ,
/* */	{ 0x116E, "EFI", "Electronics for Imaging", "*" } ,
/* */	{ 0x116F, "WkSta. Tech.", "Workstation Technology" } ,
	
		{ 0x1170, "Inventec", "Inventec Corporation" } ,
		{ 0x1171, "Lough. Sound", "Loughborough Sound Images PLC" } ,
		{ 0x1172, "Altera", "Altera Corporation","*" } ,
		{ 0x1173, "Adobe", "Adobe Systems Inc." } ,
		{ 0x1174, "Bridgeport", "Bridgeport Machines" } ,
/* */	{ 0x1175, "Mitron", "Mitron Computer Inc." } ,
/* */	{ 0x1176, "SBE", "SBE" } ,
/* */	{ 0x1177, "Silicon Eng.", "Silicon Engineering" } ,
/* */	{ 0x1178, "Alfa", "Alfa Inc." } ,
		{ 0x1179, "Toshiba", "Toshiba America Info Systems" } ,
/* */	{ 0x117A, "A-Trend", "A-Trend Technology" } ,
/* */	{ 0x117B, "LG", "Goldstar/LG Electronics Inc.", "www.leusa.com" } ,
		{ 0x117C, "Atto", "Atto Technology" } ,
/* */	{ 0x117D, "B&D", "Becton & Dickinson" } ,
/* */	{ 0x117E, "T/R", "T/R Systems" } ,
/* */	{ 0x117F, "ICS", "Integrated Circuit Systems" } ,
	
		{ 0x1180, "Ricoh", "Ricoh Company Ltd.", "www.ricoh.co.jp" } ,
/* */	{ 0x1181, "Telmatics", "Telmatics International" } ,
/* */	{ 0x1183, "Fujikura", "Fujikura Ltd." } ,
/* */	{ 0x1184, "Forks", "Forks Inc." } ,
/* */	{ 0x1185, "Dataworld", "Dataworld" } ,
/* */	{ 0x1186, "D-Link", "D-Link System Inc." } ,
		{ 0x1187, "ATL", "Advanced Technology Laboratories Inc." } ,
/* */	{ 0x1188, "Shima", "Shima Seiki Manufacturing Ltd." } ,
		{ 0x1189, "Matsushita", "Matsushita Electronics Company Ltd." } ,
/* */	{ 0x118A, "Hilevel", "Hilevel Technology" } ,
/* */	{ 0x118B, "Hypertec", "Hypertec Pty Ltd." } ,
		{ 0x118C, "Corollary", "Corollary Inc." } ,
/* */	{ 0x118D, "BitFlow", "BitFlow Inc." } ,
/* */	{ 0x118E, "Hermstedt", "Hermstedt GmbH" } ,
/* */	{ 0x118F, "Green", "Green Logic" } ,
	
		{ 0x1191, "Acard Technology", "Acard Technology Corporation" } ,
/* */	{ 0x1192, "Densan", "Densan Company Ltd." } ,
/* */	{ 0x1193, "Zeitnet", "Zeitnet Inc." } ,
/* */	{ 0x1194, "Toucan", "Toucan Technology" } ,
		{ 0x1195, "Ratoc", "Ratoc System Inc." } ,
/* */	{ 0x1196, "Hytec", "Hytec Electronics Ltd." } ,
		{ 0x1197, "Gage", "Gage Applied Sciences Inc." } ,
/* */	{ 0x1198, "Lambda", "Lambda Systems Inc." } ,
/* */	{ 0x1199, "Attachmate", "Attachmate Corporation" } ,
		{ 0x119A, "MindShare", "MindShare Inc." } ,
/* */	{ 0x119B, "Omega", "Omega Micro Inc." } ,
/* */	{ 0x119C, "ITI", "Information Technology Inst." } ,
		{ 0x119D, "Bug", "Bug Inc." } ,
/* */	{ 0x119E, "Fujitsu", "Fujitsu" } ,
		{ 0x119F, "Bull", "Bull Hn Information Systems" } ,
	
/* */	{ 0x11A0, "Convex", "Convex Computer Corporation" } ,
		{ 0x11A1, "Hamamatsu", "Hamamatsu Photonics K.K." } ,
/* */	{ 0x11A2, "Sierra", "Sierra Research and Technology" } ,
/* */	{ 0x11A3, "Deuretzbacher", "Deuretzbacher GmbH & Company Eng. KG" } ,
/* */	{ 0x11A4, "Barco", "Barco" } ,
/* */	{ 0x11A5, "MicroUnity", "MicroUnity Systems Engineering Inc." } ,
/* */	{ 0x11A6, "Pure Data", "Pure Data" } ,
/* */	{ 0x11A7, "Power Comp.", "Power Computing Corporation" } ,
/* */	{ 0x11A8, "Systech", "Systech Corporation" } ,
		{ 0x11A9, "InnoSys", "InnoSys Inc." } ,
		{ 0x11AA, "Actel", "Actel" } ,
		{ 0x11AB, "Galileo", "Galileo Technology Ltd." } ,
/* */	{ 0x11AC, "Canon", "Canon Information Systems" } ,
/* */	{ 0x11AD, "Lite-On", "Lite-On Communications Inc." } ,
		{ 0x11AE, "Scitex", "Scitex Corporation Ltd." } ,
		{ 0x11AF, "Avid", "Avid Technology Inc." } ,
	
		{ 0x11B0, "V3", "V3 Semiconductor Inc." } ,
/* */	{ 0x11B1, "Apricot", "Apricot Computers" } ,
		{ 0x11B2, "Kodak", "Eastman Kodak" } ,
/* */	{ 0x11B3, "Barr", "Barr Systems Inc." } ,
/* */	{ 0x11B4, "Leitch", "Leitch Technology International" } ,
/* */	{ 0x11B5, "Radstone", "Radstone Technology Plc" } ,
/* */	{ 0x11B6, "United Video", "United Video Corporation" } ,
/* */	{ 0x11B7, "Motorola", "Motorola", "www.mot.com" } ,
/* */	{ 0x11B8, "Xpoint", "Xpoint Technologies Inc." } ,
		{ 0x11B9, "Pathlight", "Pathlight Technology Inc." } ,
/* */	{ 0x11BA, "Videotron", "Videotron Corporation" } ,
/* */	{ 0x11BB, "Pyramid", "Pyramid Technology" } ,
/* */	{ 0x11BC, "Net. Periph.", "Network Peripherals Inc." } ,
/* */	{ 0x11BD, "Pinnacle", "Pinnacle Systems Inc." } ,
/* */	{ 0x11BE, "IMI", "International Microcircuits Inc." } ,
		{ 0x11BF, "Astrodesign", "Astrodesign Inc." } ,
	
/* */	{ 0x11C0, "HP", "Hewlett-Packard", "*" } ,
/* */	{ 0x11C1, "AT&T", "AT&T Microelectronics" } ,
/* */	{ 0x11C2, "Sand", "Sand Microelectronics" } ,
/* */	{ 0x11C3, "NEC", "NEC Corporation" } ,
		{ 0x11C4, "Doc. Tech.", "Document Technologies Inc." } ,
/* */	{ 0x11C5, "Shiva", "Shiva Corporation" } ,
		{ 0x11C6, "Dainippon", "Dainippon Screen Mfg. Company Ltd." } ,
/* */	{ 0x11C7, "D.C.M.", "D.C.M. Data Systems" } ,
		{ 0x11C8, "Dolphin", "Dolphin Interconnect Solutions AS" } ,
/* */	{ 0x11C9, "MAGMA", "MAGMA" } ,
		{ 0x11CA, "LSI Sys.", "LSI Systems Inc." } ,
		{ 0x11CB, "Specialix", "Specialix International Ltd." } ,
/* */	{ 0x11CC, "M&K", "Michels & Kleberhoff Computer GmbH" } ,
/* */	{ 0x11CD, "HAL", "HAL Computer Systems Inc." } ,
		{ 0x11CE, "Netaccess", "Netaccess" } ,
/* */	{ 0x11CF, "PEC", "Pioneer Electronic Corporation" } ,
	
		{ 0x11D0, "Lockheed", "Lockheed Martin Federal Systems - Manassas" } ,
/* */	{ 0x11D1, "AuraVision", "AuraVision Corporation", "*" } ,
		{ 0x11D2, "Intercom", "Intercom Inc." } ,
/* */	{ 0x11D3, "Trancell", "Trancell Systems Inc." } ,
		{ 0x11D4, "AD", "Analog Devices" } ,
		{ 0x11D5, "Ikon", "Ikon Corporation" } ,
/* */	{ 0x11D6, "Tekelec", "Tekelec Technologies" } ,
/* */	{ 0x11D7, "Trenton", "Trenton Terminals Inc." } ,
/* */	{ 0x11D8, "ITD", "Image Technologies Development" } ,
		{ 0x11D9, "Tec", "Tec Corporation" } ,
		{ 0x11DA, "Novell", "Novell", "*" } ,
		{ 0x11DB, "Sega", "Sega Enterprises Ltd." } ,
/* */	{ 0x11DC, "Questra", "Questra Corporation" } ,
/* */	{ 0x11DD, "Crosfield", "Crosfield Electronics Ltd." } ,
/* */	{ 0x11DE, "Zoran", "Zoran Corporation", "*" } ,
/* */	{ 0x11DF, "New Wave", "New Wave Pdg" } ,
	
/* */	{ 0x11E0, "Cray", "Cray Communications A/S" } ,
		{ 0x11E1, "Gec Plessey", "Gec Plessey Semi Inc." } ,
/* */	{ 0x11E2, "Samsung", "Samsung Information Systems America" } ,
/* */	{ 0x11E3, "Quicklogic", "Quicklogic Corporation" } ,
/* */	{ 0x11E4, "Second Wave", "Second Wave Inc." } ,
/* */	{ 0x11E5, "IIX", "IIX Consulting" } ,
/* */	{ 0x11E6, "Mitsui", "Mitsui-Zosen System Research" } ,
/* */	{ 0x11E7, "Toshiba", "Toshiba America, Elec. Co" } ,
/* */	{ 0x11E8, "DPSI", "Digital Processing Systems Inc." } ,
/* */	{ 0x11E9, "Highwater", "Highwater Designs Ltd." } ,
/* */	{ 0x11EA, "Elsag", "Elsag Bailey" } ,
/* */	{ 0x11EB, "Formation", "Formation Inc." } ,
		{ 0x11EC, "Coreco", "Coreco Inc." } ,
/* */	{ 0x11ED, "Mediamatics", "Mediamatics" } ,
/* */	{ 0x11EE, "Dome", "Dome Imaging Systems Inc." } ,
/* */	{ 0x11EF, "Nicolet", "Nicolet Technologies BV" } ,
	
/* */	{ 0x11F0, "Compu-Shack", "Compu-Shack GmbH" } ,
		{ 0x11F1, "Symbios", "Symbios Logic Inc." } ,
/* */	{ 0x11F2, "Pic-Tel", "Picture Tel Japan KK" } ,
/* */	{ 0x11F3, "Keithley", "Keithley Metrabyte" } ,
/* */	{ 0x11F4, "Kinetic", "Kinetic Systems Corporation" } ,
/* */	{ 0x11F5, "Comp Dev", "Computing Devices Intl" } ,
/* */	{ 0x11F6, "Powermatic", "Powermatic Data Systems Ltd." } ,
/* */	{ 0x11F7, "S-A", "Scientific Atlanta" } ,
		{ 0x11F8, "PMC-Sierra", "PMC-Sierra Inc." } ,
		{ 0x11F9, "I-Cube", "I-Cube Inc." } ,
/* */	{ 0x11FA, "Kasan", "Kasan Electronics Company Ltd." } ,
/* */	{ 0x11FB, "Datel", "Datel Inc." } ,
/* */	{ 0x11FC, "Silicon Magic", "Silicon Magic" } ,
/* */	{ 0x11FD, "High Street", "High Street Consultants" } ,
/* */	{ 0x11FE, "Comtrol", "Comtrol Corporation" } ,
/* */	{ 0x11FF, "Scion", "Scion Corporation" } ,

/* */	{ 0x1200, "CSS", "CSS Corporation" } ,
		{ 0x1201, "Vista", "Vista Controls Corporation" } ,
/* */	{ 0x1202, "Network Gen", "Network General Corporation" } ,
/* */	{ 0x1203, "Agfa", "Bayer Corporation, Agfa Div" } ,
		{ 0x1204, "Lattice", "Lattice Semiconductor Corporation" } ,
		{ 0x1205, "Array", "Array Corporation" } ,
		{ 0x1206, "Amdahl", "Amdahl Corporation" } ,
/* */	{ 0x1208, "Parsytec", "Parsytec GmbH" } ,
/* */	{ 0x1209, "Sci Sys", "Sci Systems Inc." } ,
/* */	{ 0x120A, "Synaptel", "Synaptel" } ,
/* */	{ 0x120B, "Adaptive", "Adaptive Solutions" } ,
/* */	{ 0x120D, "Comp Labs", "Compression Labs Inc." } ,
/* */	{ 0x120E, "Cyclades", "Cyclades Corporation" } ,
/* */	{ 0x120F, "Essential", "Essential Communications" } ,

/* */	{ 0x1210, "Hyperparallel", "Hyperparallel Technologies" } ,
/* */	{ 0x1211, "Braintech", "Braintech Inc." } ,
/* */	{ 0x1212, "Kingston", "Kingston Technology Corporation" } ,
/* */	{ 0x1213, "AISI", "Applied Intelligent Systems Inc." } ,
/* */	{ 0x1214, "Perf Tech", "Performance Technologies Inc." } ,
/* */	{ 0x1215, "Interware", "Interware Co Ltd." } ,
		{ 0x1216, "Purup", "Purup Eskofot A/S" } ,
		{ 0x1217, "O2Micro", "O2Micro Inc." } ,
/* */	{ 0x1218, "Hybricon", "Hybricon Corporation" } ,
/* */	{ 0x1219, "First Virtual", "First Virtual Corporation" } ,
		{ 0x121A, "3dfx", "3dfx Interactive Inc.", "*" } ,
		{ 0x121B, "ATM", "Advanced Telecommunications Modules" } ,
/* */	{ 0x121C, "Nippon Texa", "Nippon Texa Company Ltd." } ,
/* */	{ 0x121D, "Lippert", "Lippert Automationstechnik GmbH" } ,
/* */	{ 0x121E, "CSPI", "CSPI" } ,
/* */	{ 0x121F, "Arcus", "Arcus Technology Inc." } ,

/* */	{ 0x1220, "Ariel", "Ariel Corporation" } ,
		{ 0x1221, "Contec", "Contec Company Ltd." } ,
/* */	{ 0x1222, "Ancor", "Ancor Communications Inc." } ,
		{ 0x1223, "Heurikon", "Heurikon/Computer Products" } ,
/* */	{ 0x1224, "Int. Img.", "Interactive Images" } ,
/* */	{ 0x1225, "Power IO", "Power I/O Inc." } ,
		{ 0x1227, "Tech-Source", "Tech-Source" } ,
/* */	{ 0x1228, "Norsk", "Norsk Elektro Optikk A/S" } ,
/* */	{ 0x1229, "Data Kin", "Data Kinesis Inc." } ,
		{ 0x122A, "Int. Telecom", "Integrated Telecom" } ,
/* */	{ 0x122B, "LG Ind.", "LG Industrial Systems Company Ltd." } ,
		{ 0x122C, "Sican", "Sican GmbH" } ,
		{ 0x122D, "Aztech", "Aztech System Ltd." } ,
		{ 0x122E, "Xyratex", "Xyratex" } ,
/* */	{ 0x122F, "Andrew", "Andrew Corporation" } ,

/* */	{ 0x1230, "Fishcamp", "Fishcamp Engineering" } ,
/* */	{ 0x1231, "W McCoach", "Woodward McCoach Inc." } ,
/* */	{ 0x1232, "GPT", "GPT Ltd." } ,
/* */	{ 0x1233, "Bus-Tech", "Bus-Tech Inc." } ,
/* */	{ 0x1234, "Technical", "Technical Corporation" } ,
		{ 0x1235, "Smart", "Smart Modular Technologies Inc." } ,
/* */	{ 0x1236, "Sigma", "Sigma Designs Corporation" } ,
/* */	{ 0x1237, "Alta Tech", "Alta Technology Corporation" } ,
/* */	{ 0x1238, "Adtran", "Adtran" } ,
/* */	{ 0x1239, "3DO", "The 3DO Company" } ,
/* */	{ 0x123A, "Visicom", "Visicom Laboratories Inc." } ,
/* */	{ 0x123B, "Seeq", "Seeq Technology Inc." } ,
		{ 0x123C, "Century Sys", "Century Systems Inc." } ,
		{ 0x123D, "EDT", "Engineering Design Team Inc." } ,
/* */	{ 0x123F, "C-Cube", "C-Cube Microsystems" } ,

/* */	{ 0x1240, "Marathon", "Marathon Technologies Corporation" } ,
		{ 0x1241, "DSC", "DSC Communications" } ,
/* */	{ 0x1243, "Delphax", "Delphax" } ,
		{ 0x1244, "AVM", "AVM Audiovisuelles Mktf & Computer System GmbH", "www.avm.de" } ,
/* */	{ 0x1245, "APD", "APD S.A." } ,
/* */	{ 0x1246, "Dipix", "Dipix Technologies Inc." } ,
/* */	{ 0x1247, "Xylon", "Xylon Research Inc." } ,
/* */	{ 0x1248, "Central Data", "Central Data Corporation" } ,
/* */	{ 0x1249, "Samsung", "Samsung Electronics Company Ltd." } ,
/* */	{ 0x124A, "AEG", "AEG Electrocom GmbH" } ,
		{ 0x124B, "GreenSpring", "SBS/GreenSpring Modular I/O" } ,
/* */	{ 0x124C, "Solitron", "Solitron Technologies Inc." } ,
/* */	{ 0x124D, "Stallion", "Stallion Technologies" } ,
/* */	{ 0x124E, "Cylink", "Cylink" } ,
/* */	{ 0x124F, "Infortrend", "Infortrend Technology Inc." } ,

		{ 0x1250, "Hitachi", "Hitachi Microcomputer System Ltd." } ,
		{ 0x1251, "VLSI Sol.", "VLSI Solution OY" } ,
/* */	{ 0x1253, "Guzik", "Guzik Technical Enterprises" } ,
/* */	{ 0x1254, "Linear Systems", "Linear Systems Ltd." } ,
		{ 0x1255, "Optibase", "Optibase Ltd." } ,
/* */	{ 0x1256, "Perceptive", "Perceptive Solutions Inc." } ,
/* */	{ 0x1257, "Vertex", "Vertex Networks Inc." } ,
		{ 0x1258, "Gilbarco", "Gilbarco Inc." } ,
		{ 0x1259, "Allied Tsyn", "Allied Telesyn International" } ,
/* */	{ 0x125A, "ABB Pwr", "ABB Power Systems" } ,
		{ 0x125B, "Asix", "Asix Electronics Corporation" } ,
		{ 0x125C, "Aurora", "Aurora Technologies Inc." } ,
/* */	{ 0x125D, "ESS", "ESS Technology" } ,
/* */	{ 0x125E, "Specvideo", "Specialvideo Engineering SRL" } ,
/* */	{ 0x125F, "Concurrent", "Concurrent Technologies Inc." } ,

		{ 0x1260, "Harris", "Harris Semiconductor" } ,
		{ 0x1261, "Matsushita", "Matsushita-Kotobuki Electronics Industries, Ltd." } ,
		{ 0x1262, "ES Comp.", "ES Computer Company Ltd." } ,
/* */	{ 0x1263, "Sonic Sol.", "Sonic Solutions" } ,
		{ 0x1264, "Aval Nag.", "Aval Nagasaki Corporation" } ,
/* */	{ 0x1265, "Casio", "Casio Computer Company Ltd." } ,
		{ 0x1266, "Microdyne", "Microdyne Corporation" } ,
/* */	{ 0x1267, "SA Telecom", "S.A. Telecommunications" } ,
		{ 0x1268, "Tektronix", "Tektronix" } ,
/* */	{ 0x1269, "Thomson-CSF", "Thomson-CSF/TTM" } ,
/* */	{ 0x126A, "Lexmark", "Lexmark International Inc.", "*" } ,
/* */	{ 0x126B, "Adax", "Adax Inc." } ,
/* */	{ 0x126C, "NorTel", "Northern Telecom" } ,
/* */	{ 0x126D, "Splash", "Splash Technology Inc." } ,
/* */	{ 0x126E, "Sumitomo", "Sumitomo Metal Industries Ltd." } ,
		{ 0x126F, "Sil Motion", "Silicon Motion Inc." } ,

/* */	{ 0x1270, "Olympus", "Olympus Optical Company Ltd." } ,
/* */	{ 0x1271, "GW Instr.", "GW Instruments" } ,
/* */	{ 0x1272, "Telematics", "Telematics International" } ,
/* */	{ 0x1273, "Hughes", "Hughes Network Systems" } ,
		{ 0x1274, "Ensoniq", "Ensoniq Corporation", "*" } ,
		{ 0x1275, "NetApp", "Network Appliance Corporation" } ,
		{ 0x1276, "Sw Net Tech", "Switched Network Technologies Inc." } ,
/* */	{ 0x1277, "Comstream", "Comstream" } ,
		{ 0x1278, "Transtech", "Transtech Parallel Systems Ltd." } ,
		{ 0x1279, "Transmeta", "Transmeta Corporation" } ,
		{ 0x127A, "Rockwell", "Rockwell International" } ,
/* */	{ 0x127B, "Pixera", "Pixera Corporation" } ,
/* */	{ 0x127C, "Crosspoint", "Crosspoint Solutions Inc." } ,
		{ 0x127D, "Vela Res", "Vela Research" } ,
/* */	{ 0x127E, "Winnow", "Winnov, L.P." } ,
		{ 0x127F, "Fujifilm", "Fujifilm" } ,

		{ 0x1280, "Photoscript", "Photoscript Group Ltd." } ,
		{ 0x1281, "Yokogawa", "Yokogawa Electric Corporation" } ,
		{ 0x1282, "Davicom", "Davicom Semiconductor Inc." } ,
		{ 0x1283, "ITExpress", "Integrated Technology Express Inc." } ,
/* */	{ 0x1284, "Sahara", "Sahara Networks Inc." } ,
/* */	{ 0x1285, "Plat Tech", "Platform Technologies Inc." } ,
		{ 0x1286, "Mazet", "Mazet GmbH" } ,
		{ 0x1287, "LuxSonor", "LuxSonor Inc." } ,
/* */	{ 0x1288, "Timestep", "Timestep Corporation" } ,
		{ 0x1289, "AVC Tech", "AVC Technology Inc." } ,
		{ 0x128A, "Asante", "Asante Technologies Inc." } ,
		{ 0x128B, "Transwitch", "Transwitch Corporation" } ,
		{ 0x128C, "Sonoma", "Sonama Systems Inc." } ,
		{ 0x128D, "G2 Net", "G2 Networks Inc." } ,
		{ 0x128E, "Hoon Tech", "Hoon Tech Company Ltd." } ,
		{ 0x128F, "Tateno", "Tateno Dennou Inc." } ,

/* */	{ 0x1290, "Sord", "Sord Computer Corporation" } ,
/* */	{ 0x1291, "NCS Comp", "NCS Computer Italia" } ,
		{ 0x1292, "Tritech", "Tritech Microelectronics Inc." } ,
/* */	{ 0x1293, "M Reality", "Media Reality Technology" } ,
		{ 0x1294, "Rhetorex", "Rhetorex Inc." } ,
/* */	{ 0x1295, "Imagenation", "Imagenation Corporation" } ,
/* */	{ 0x1296, "Kofax", "Kofax Image Products" } ,
/* */	{ 0x1297, "Holco", "Holco Enterprise" } ,
/* */	{ 0x1298, "Spellcaster", "Spellcaster Telecommunications Inc." } ,
		{ 0x1299, "Know Tech", "Knowledge Technology Laboratories" } ,
/* */	{ 0x129A, "VMETRO", "VMETRO" } ,
/* */	{ 0x129B, "Img Access", "Image Access" } ,
		{ 0x129C, "Jaton", "Jaton Corporation" },
/* */	{ 0x129D, "CompCore", "CompCore Multimedia Inc." } ,
		{ 0x129E, "Victor", "Victor Company of Japan, Ltd." } ,
		{ 0x129F, "OEC Med", "OEC Medical Systems Inc." } ,

		{ 0x12A0, "A-B", "Allen Bradley Company" } ,
/* */	{ 0x12A1, "Simpact", "Simpact Inc." } ,
		{ 0x12A2, "NewGen", "NewGen Systems Corporation" } ,
		{ 0x12A3, "Lucent", "Lucent Technologies" } ,
		{ 0x12A4, "NTT Elect", "NTT Electronics Technology Company" } ,
/* */	{ 0x12A5, "Vision Dyn", "Vision Dynamics Ltd." } ,
/* */	{ 0x12A6, "Scalable", "Scalable Networks Inc." } ,
/* */	{ 0x12A7, "AMO", "AMO GmbH" } ,
/* */	{ 0x12A8, "News Datacom", "News Datacom" } ,
/* */	{ 0x12A9, "Xiotech", "Xiotech Corporation" } ,
/* */	{ 0x12AA, "SDL", "SDL Communications Inc." } ,
/* */	{ 0x12AB, "Yuan Yuan", "Yuan Yuan Enterprise Company Ltd." } ,
/* */	{ 0x12AC, "MeasureX", "MeasureX Corporation" } ,
		{ 0x12AD, "Multidata", "Multidata GmbH" } ,
		{ 0x12AE, "Alteon", "Alteon Networks Inc." } ,
		{ 0x12AF, "TDK USA", "TDK USA Corporation" } ,

/* */	{ 0x12B0, "Jorge Sci", "Jorge Scientific Corporation" } ,
/* */	{ 0x12B1, "GammaLink", "GammaLink" } ,
		{ 0x12B2, "Gen Signal", "General Signal Networks" } ,
/* */	{ 0x12B3, "Inter-Face", "Inter-Face Company Ltd." } ,
/* */	{ 0x12B4, "Future Tel", "Future Tel Inc." } ,
/* */	{ 0x12B5, "Granite", "Granite Systems Inc." } ,
		{ 0x12B6, "Nat Micro", "Natural Microsystems" } ,
		{ 0x12B7, "Acumen", "Cognex Modular Vision Systems - Acumen Inc." } ,
/* */	{ 0x12B8, "Korg", "Korg" } ,
		{ 0x12B9, "US Robotics", "US Robotics/3Com Corporation", "www.3com.com" } ,
		{ 0x12BA, "Bittware", "Bittware Research Systems Inc." } ,
/* */	{ 0x12BB, "Nippon Uni", "Nippon Unisoft Corporation" } ,
/* */	{ 0x12BC, "Array Micro", "Array Microsystems" } ,
/* */	{ 0x12BD, "Computerm", "Computerm Corporation" } ,
		{ 0x12BE, "Anchor Chips", "Anchor Chips Inc." } ,
		{ 0x12BF, "Fujifilm", "Fujifilm Microdevices" } ,

		{ 0x12C0, "Infimed", "Infimed" } ,
		{ 0x12C1, "GMM Res", "GMM Research Corporation" } ,
		{ 0x12C2, "Mentec", "Mentec Ltd." } ,
		{ 0x12C3, "Holtek", "Holtek Microelectronics Inc." } ,
		{ 0x12C4, "Conn Tech", "Connect Tech Inc." } ,
/* */	{ 0x12C5, "PicturEl", "Picture Elements Inc." } ,
		{ 0x12C6, "Mitani", "Mitani Corporation" } ,
		{ 0x12C7, "Dialogic", "Dialogic Corporation" } ,
		{ 0x12C8, "G Force", "G Force Company Ltd." } ,
		{ 0x12C9, "Gigi Ops", "Gigi Operations" } ,
		{ 0x12CA, "ICE", "Integrated Computing Engines Inc." } ,
/* */	{ 0x12CB, "Antex", "Antex Electronics Corporation" } ,
/* */	{ 0x12CC, "Pluto", "Pluto Technologies International" } ,
		{ 0x12CD, "Aims Lab", "Aims Lab" } ,
/* */	{ 0x12CE, "Netspeed", "Netspeed Inc." } ,
/* */	{ 0x12CF, "Prophet", "Prophet Systems Inc." } ,

/* */	{ 0x12D0, "GDE Sys", "GDE Systems Inc." } ,
/* */	{ 0x12D1, "PsiTech", "PsiTech" } ,
/* */	{ 0x12D2, "NVidia", "NVidia / SGS Thomson", "*" } ,
		{ 0x12D3, "Vingmed", "Vingmed Sound A/S" } ,
		{ 0x12D4, "DGM&S", "DGM&S" } ,
		{ 0x12D5, "Equator", "Equator Technologies" } ,
		{ 0x12D6, "Analogic", "Analogic Corporation" } ,
/* */	{ 0x12D7, "Biotronic", "Biotronic SRL" } ,
/* */	{ 0x12D8, "Pericom", "Pericom Semiconductor" } ,
		{ 0x12D9, "Aculab", "Aculab Plc." } ,
		{ 0x12DA, "True Time", "True Time Inc." } ,
/* */	{ 0x12DB, "Annapolis", "Annapolis Micro Systems Inc." } ,
/* */	{ 0x12DC, "Symicron", "Symicron Computer Communication Ltd." } ,
/* */	{ 0x12DD, "MGI", "Management Graphics Inc." } ,
/* */	{ 0x12DE, "Rainbow", "Rainbow Technologies" } ,
		{ 0x12DF, "SBS Tech", "SBS Technologies Inc." } ,

		{ 0x12E0, "Chase", "Chase Research Plc." } ,
/* */	{ 0x12E1, "Nintendo", "Nintendo Company Ltd." } ,
/* */	{ 0x12E2, "Datum", "Datum Inc., Bancomm-Timing Division" } ,
/* */	{ 0x12E3, "Imation", "Imation Corporation - Medical Imaging Systems" } ,
		{ 0x12E4, "Brooktrout", "Brooktrout Technology Inc." } ,
		{ 0x12E5, "Apex Semi", "Apex Semiconductor Inc." },
		{ 0x12E6, "Cirel", "Cirel Systems" } ,
		{ 0x12E7, "Sebring", "Sebring Systems Inc." } ,
		{ 0x12E8, "CRISC", "CRISC Corporation" } ,
		{ 0x12E9, "GE Spacenet", "GE Spacenet" } ,
		{ 0x12EA, "Real Vision", "Real Vision Inc." } ,
		{ 0x12EB, "Aureal", "Aureal Semiconductor", "*" } ,
		{ 0x12EC, "3A Intl", "3A International Inc." } ,
		{ 0x12ED, "Optivision", "Optivision Inc." } ,
		{ 0x12EE, "Orange Micro", "Orange Micro" } ,
		{ 0x12EF, "Vienna", "Vienna Systems" } ,

		{ 0x12F0, "Pentek", "Pentek" } ,
		{ 0x12F1, "Sorenson", "Sorenson Vision Inc." } ,
/* */	{ 0x12F2, "Gammagraphx", "Gammagraphx Inc." } ,
		{ 0x12F4, "Megatel", "Megatel" } ,
		{ 0x12F5, "Forks", "Forks" } ,
/* */	{ 0x12F6, "Dawson Fr", "Dawson France" } ,
		{ 0x12F7, "Cognex", "Cognex" } ,
		{ 0x12F8, "Electronic-Design", "Electronic-Design GmbH" } ,
		{ 0x12F9, "FFT", "Four Fold Ltd." } ,
		{ 0x12FB, "Spectrum Signal", "Spectrum Signal Processing" },
		{ 0x12FC, "Captial", "Capital Equipment Corporation" },
		{ 0x12FD, "i2S", "i2S" },
		{ 0x12FE, "ESD", "ESD Electronic System Design GmbH" } ,
		{ 0x12FF, "Lexicon", "Lexicon" },

		{ 0x1300, "Harman", "Harman International Industries Inc." },
		{ 0x1302, "Comp Science", "Computer Science Corporation" },
		{ 0x1303, "Innovative", "Innovative Integration" },
		{ 0x1304, "Juniper", "Juniper Networks " },
		{ 0x1305, "NetPhone", "NetPhone Inc." },
		{ 0x1306, "Duet", "Duet Technologies" },
		{ 0x1307, "Comp Boards", "Computer Boards" },
		{ 0x1308, "Jato", "Jato Technologies Inc." },
		{ 0x1309, "AB Semicon", "AB Semicon Ltd." } ,
		{ 0x130A, "Mitsubishi", "Mitsubishi Electric MicroComputer" },
		{ 0x130B, "Colorgraphic", "Colorgraphic Communications Corporation" },
		{ 0x130C, "AMBEX", "AMBEX Technologies Inc." },
		{ 0x130D, "Accelerix", "Accelerix Inc." },	
		{ 0x130E, "Honeywell", "Yamatake-Honeywell Company Ltd." },
		{ 0x130F, "Advanet", "Advanet Inc." },
	
		{ 0x1310, "Gespac", "Gespac" },
		{ 0x1311, "VideoServer", "VideoServer Inc." },
		{ 0x1312, "Acuity", "Acuity Imaging Inc." },
		{ 0x1313, "Yaskawa", "Yaskawa Electric Company" },
		{ 0x1316, "Teradyne", "Teradyne Inc." },
		{ 0x1317, "Bridgecom", "Bridgecom Inc." },
		{ 0x1318, "Packet", "Packet Engines Inc." },
		{ 0x1319, "ForteMedia", "ForteMedia Inc." },
		{ 0x131A, "Finisar", "Finisar Corporation" },
		{ 0x131C, "Nippon", "Nippon Electro-Sensory Devices Corporation" },
		{ 0x131D, "Sysmic Inc." },
		{ 0x131E, "Xinex", "Xinex Networks Inc." },
		{ 0x131F, "SIIG", "SIIG Inc." },
		
		{ 0x1322, "MTT", "MTT Co. Ltd." },
		{ 0x1325, "Salix", "Salix Technologies Inc." },
		{ 0x1326, "SeaChange", "SeaChange International" },
		{ 0x1328, "Quadrant", "Quadrant International" },
		{ 0x132B, "BroadBand", "BroadBand Technologies" },

		{ 0x1330, "MMC", "MMC Networks" },
		{ 0x1331, "RadiSys", "RadiSys Corporation" } ,
		{ 0x1332, "MicroMem", "Micro Memory" },
		{ 0x1334, "Redcreek", "Redcreek Communications Inc." },
		{ 0x1335, "Videomail", "Videomail Inc." } ,
		{ 0x1337, "Third Planet", "Third Planet Publishing" },
		{ 0x1338, "BT", "BT Electronics" },
		{ 0x133A, "VTel", "VTel Corporation" },
		{ 0x133B, "Softcom", "Softcom Microsystems" },
		{ 0x133C, "Holontech", "Holontech Corporation" },
		{ 0x133D, "SSTech", "S S Technologies" },
		{ 0x133E, "VirtualComp", "Virtual Computer Corporation" },
		{ 0x133F, "SCM", "SCM Microsystems" },

		{ 0x1340, "Atalla Corporation" },
		{ 0x1341, "Kyoto Microcomputer Company" },
		{ 0x1342, "Promax Systems Inc." },
		{ 0x1343, "Phylon", "Phylon Communications Inc." },
		{ 0x1344, "Crucial Technology" },
		{ 0x1345, "Arescom", "Arescom Inc." },
		{ 0x1347, "Odetics", "Odetics" } ,
		{ 0x1349, "Sumitomo", "Sumitomo Eletric Industries, Ltd." },
		{ 0x134A, "DTC", "DTC Technology Corporation" },
		{ 0x134B, "Ark Research Corporation" },
		{ 0x134C, "Chori Joho Systems Company Ltd." },
		{ 0x134D, "Pctel", "Pctel Inc." },
		{ 0x134E, "CSTI", "CSTI" },
		{ 0x134F, "Algo", "Algo System Company Ltd." },

		{ 0x1350, "Systec", "Systec Company Ltd." },
		{ 0x1351, "Sonix", "Sonix Inc./3Com Corporation" },
		{ 0x1353, "Dassault","Dassault A.T." },
		{ 0x1354, "dWave", "dWave System Inc." },
		{ 0x1355, "Kratos", "Kratos Analytical Ltd." },
		{ 0x1356, "Logical", "The Logical Company" },
		{ 0x1359, "Prisa", "Prisa Networks" },
		{ 0x135A, "Brain Boxes", "Brain Boxes" },
		{ 0x135B, "Giganet", "Giganet Inc." },
		{ 0x135C, "Quatech", "Quatech Inc." },
		{ 0x135D, "ABB Network Partner", "ABB Network Partner AB" } ,
		{ 0x135E, "Sealevel", "Sealevel Systems Inc." },
		{ 0x135F, "I-Data", "I-Data International A-S" },

		{ 0x1360, "Meinberg Funkuhren" },
		{ 0x1361, "Soliton Systems K.K." },
		{ 0x1362, "Fujifacom", "Fujifacom Corporation"} ,
		{ 0x1363, "Phoenix", "Phoenix Technology Ltd." },
		{ 0x1364, "ATM", "ATM Communications Inc." },
		{ 0x1365, "Hypercope", "Hypercope GmbH" },
		{ 0x1366, "Teijin Seiki Company Ltd." },
		{ 0x1367, "Hitachi Zosen", "Hitachi Zosen Corporation" },
		{ 0x1368, "Skyware", "Skyware Corporation" },
		{ 0x1369, "Digigram", "Digigram" },
		{ 0x136A, "High Soft", "High Soft Tech" },
		{ 0x136B, "Kawasaki Steel", "Kawasaki Steel Corporation" },
		{ 0x136C, "Adtek", "Adtek System Science Company Ltd." },
		{ 0x136D, "Gigalabs", "Gigalabs Inc." },
		{ 0x136F, "Applied Magic", "Applied Magic Inc." },

		{ 0x1370, "ATL", "ATL Products" },
		{ 0x1371, "CNet", "CNet Technology Inc." },
		{ 0x1373, "Silicon Vision", "Silicon Vision Inc." },
		{ 0x1374, "Silicom", "Silicom Ltd." },
		{ 0x1375, "Argosystems", "Argosystems Inc." },
		{ 0x1376, "LMC", "LMC" },
		{ 0x1377, "EEPD", "Eletronic Equipment Production & Distribution GmbH" },
		{ 0x1378, "Telemann", "Telemann Company Ltd." },
		{ 0x1379, "Asahi Kasei", "Asahi Kasei Microsystems Company Ltd." },
		{ 0x137A, "Unicorn", "Mark of the Unicorn Inc." },
		{ 0x137B, "PPT Vision", "PPT Vision" },
		{ 0x137C, "Iwatsu", "Iwatsu Eletric Company Ltd." },
		{ 0x137D, "Dynachip", "Dynachip Corporation" },
		{ 0x137E, "PTSC", "Patriot Scientific Corporation" } ,
		{ 0x137F, "Japan Satellite", "Japan Satellite Systems Inc." },

		{ 0x1380, "Sanritz", "Sanritz Automation Company Ltd. "},
		{ 0x1381, "Brains", "Brains Company Ltd." },
		{ 0x1382, "Marian", "Marian - Electronic & Software" },
		{ 0x1383, "Controlnet", "Controlnet Inc." },
		{ 0x1384, "Reality Sim", "Reality Simulation Systems Inc." },
		{ 0x1385, "Netgear", "Netgear" },
		{ 0x1386, "Video Domain", "Video Domain Technologies" },
		{ 0x1387, "Systran", "Systran Corporation" },
		{ 0x1388, "Hitachi", "Hitachi Information Technology Ltd." },
		{ 0x1389, "Applicom", "Applicom International" },
		{ 0x138A, "Fusion", "Fusion Micromedia Corporation" },
		{ 0x138B, "Tokimec", "Tokimec Inc." },
		{ 0x138C, "Silicon", "Silicon Reality" },
		{ 0x138D, "Future Techno", "Future Techno Designs Pte Ltd." },
		{ 0x138E, "Basler", "Basler GmbH" },
		{ 0x138F, "Patapsco", "Patapsco Designs Inc." },

		{ 0x1390, "Concept", "Concept Development Inc." },
		{ 0x1391, "Dev Concepts", "Development Concepts Inc." },
		{ 0x1392, "Medialight", "Medialight Inc." },
		{ 0x1393, "Moxa", "Moxa Technologies Company Ltd." },
		{ 0x1394, "Level One", "Level One Communications" },
		{ 0x1395, "Ambicom", "Ambicom Inc." },
		{ 0x1396, "Cipher", "Cipher Systems Inc." },
		{ 0x1397, "Cologne", "Cologne Chip Designs GmbH" },
		{ 0x1398, "Clarion", "Clarion Company Ltd." },
		{ 0x1399, "Rios", "Rios Systems Company Ltd." },
		{ 0x139A, "Alacritech", "Alacritech Inc." },
		{ 0x139C, "Quantum3D", "Quantum 3D Inc." },
		{ 0x139B, "Mediasonic", "Mediasonic Multimedia Systems Ltd." },
		{ 0x139D, "EPL", "EPL Ltd." },
		{ 0x139E, "Media4", "Media4" },
		{ 0x139F, "Aethra", "Aethra S.R.L." },

		{ 0x13A0, "Crystal", "Crystal Group Inc." },
		{ 0x13A1, "Kawasaki", "Kawasaki Heavy Industries Ltd." },
		{ 0x13A2, "Ositech", "Ositech Communications Inc." },
		{ 0x13A3, "Hi-Fn", "Hi-Fn" },
		{ 0x13A4, "Rascom", "Rascom Inc." },
		{ 0x13A5, "Audio Digital", "Audio Digital Imaging Inc." },
		{ 0x13A6, "Videonics", "Videonics Inc." },
		{ 0x13A7, "Teles", "Teles AG" },
		{ 0x13A8, "Exar", "Exar Corporation" },
		{ 0x13A9, "Siemens", "Siemens Medical Systems, Ultrasound Group" },
		{ 0x13AA, "Broadband", "Broadband Networks Inc." },
		{ 0x13AB, "Arcom", "Arcom Control Systems Ltd." },
		{ 0x13AC, "Motion Media", "Motion Media Technology Ltd." },
		{ 0x13AD, "Nexus", "Nexus Inc." },
		{ 0x13AE, "ALD Tech", "ALD Technology Ltd." },
		{ 0x13AF, "T.Sqware", "T.Sqware" },
	
		{ 0x13B0, "Maxspeed", "Maxspeed Corporation" },
		{ 0x13B1, "Tamura", "Tamura Corporation" },
		{ 0x13B2, "TechnoChips", "Techno Chips Company Ltd." },
		{ 0x13B3, "Lanart", "Lanart Corporation" },
		{ 0x13B4, "Wellbean", "Wellbean Company Inc." },
		{ 0x13B5, "Ark", "Ark Research Corporation" },
		{ 0x13B6, "DLoG", "DLoG GmbH" },
		{ 0x13B7, "LogicDev", "Logic Devices Inc." },
		{ 0x13B8, "Nokia", "Nokia Telecommunications OY" },
		{ 0x13B9, "Elecom", "Elecom Company Ltd." },
		{ 0x13BA, "Oxford", "Oxford Instruments" },
		{ 0x13BB, "Sanyo", "Sanyo Technosound Company Ltd." },
		{ 0x13BC, "Bitran", "Bitran Corporation" },
		{ 0x13BD, "Sharp", "Sharp Corporation" },
		{ 0x13BE, "Miroku", "Miroku Jyoho Service Company Ltd." },
		{ 0x13BF, "Sharewave", "Sharewave Inc." },

		{ 0x13C0, "Microgate", "Microgate Corporation" },
		{ 0x13C1, "3Ware", "3Ware Inc." },
		{ 0x13C2, "Technotrend", "Technotrend Systemtechnik GmbH" },
		{ 0x13C3, "Janz", "Janz Computer AG" },
		{ 0x13C4, "Phase", "Phase Metrics" },
		{ 0x13C5, "Alphi", "Alphi Technology Corporation" },
		{ 0x13C6, "Condor", "Condor Engineering Inc." },
		{ 0x13C7, "Blue Chip", "Blue Chip Technology Ltd. "},
		{ 0x13C8, "Apptech", "Apptech Inc." },
		{ 0x13C9, "Eaton", "Eaton Corporation" },
		{ 0x13CA, "Iomega", "Iomega Corporation" },
		{ 0x13CB, "Yano", "Yano Eletric Company Ltd." },
		{ 0x13CC, "Metheus Corporation" },
		{ 0x13CD, "Compatible", "Compatible Systems Corporation" },
		{ 0x13CE, "Cocom", "Cocom A/S" },
		{ 0x13CF, "Studio AV", "Studio Audio & Video Ltd." },

		{ 0x13D0, "Techsan", "Techsan Eletronics Company Ltd." },
		{ 0x13D1, "Abocom", "Abocom Systems Inc." },
		{ 0x13D2, "Shark", "Shark Multimedia Inc." },
		{ 0x13D3, "IMC", "IMC Networks" },
		{ 0x13D4, "Graphics Micro", "Graphics Microsystems Inc." },
		{ 0x13D5, "Media100", "Media 100 Inc." },
		{ 0x13D6, "KI Tech", "K.I. Technology Company Ltd." },
		{ 0x13D7, "Toshiba Engineering Corporation" },
		{ 0x13D8, "Phobos", "Phobos Corporation" },
		{ 0x13D9, "Apex PC", "Apex PC Solutions Inc. "},
		{ 0x13DA, "Intresource", "Intresource Systems Pte Ltd." },
		{ 0x13DB, "JanichKlass", "Janich & Klass Computertechnik GmbH" },
		{ 0x13DC, "Netboost", "Netboost Corporation" },
		{ 0x13DD, "Multimedia Bundle", "Multimedia Bundle Inc." },
		{ 0x13DE, "ABB Robotics", "ABB Robotics Products AB" },
		{ 0x13DF, "E-Tech", "E-Tech Inc." },

		{ 0x13E0, "GVC", "GVC Corporation" },
		{ 0x13E1, "Silicom", "Silicom Multimedia Systems Inc." },
		{ 0x13E2, "Dynamics", "Dynamics Research Corporation" },
		{ 0x13E3, "Nest", "Nest Inc." },
		{ 0x13E4, "Calculex", "Calculex Inc." },
		{ 0x13E5, "Telesoft", "Telesoft Design Ltd." },
		{ 0x13E6, "Argosy", "Argosy Research Inc." },
		{ 0x13E7, "NAC", "NAC Inc." },
		{ 0x13E8, "Chip Express", "Chip Express Corporation" },
		{ 0x13E9, "Intraserver", "Intraserver Technology Inc." },
		{ 0x13EA, "Dallas Semi", "Dallas Semiconductor" },
		{ 0x13EB, "Hauppauge", "Hauppauge Computer Works Inc." },
		{ 0x13EC, "Zydacron", "Zydacron Inc." },
		{ 0x13ED, "Raytheion", "Raytheion E-Systems" },
		{ 0x13EE, "Hayes", "Hayes Microcomputer Products Inc.", "*" },
		{ 0x13EF, "Coppercom", "Coppercom Inc." },

		{ 0x13F0, "Sundance", "Sundance Technology Inc." },
		{ 0x13F1, "Oak", "Oak Technology Inc." },
		{ 0x13F2, "Ford Micro", "Ford Microelectronics Inc." },
		{ 0x13F3, "McData", "McData Corporation" },
		{ 0x13F4, "Troika", "Troika Design Inc." },
		{ 0x13F5, "Kansai", "Kansai Eletric Company Ltd." },
		{ 0x13F6, "C-Media", "C-Media Electronics Inc." },
		{ 0x13F7, "Wildfire", "Wildfire Communications", "*" },
		{ 0x13F8, "AdLib","Ad Lib Multimedia Inc." },
		{ 0x13F9, "NTT", "NTT Advanced Technology Corporation" },
		{ 0x13FA, "Pentland", "Pentland Systems Ltd." },
		{ 0x13FB, "Aydin", "Aydin Corporation" },
		{ 0x13FC, "Comp Periph", "Computer Peripherals International" }, 
		{ 0x13FD, "Micro Science", "Micro Science Inc." },
		{ 0x13FE, "Advantech", "Advantech Company Ltd." },
		{ 0x13FF, "Silicon Spice", "Silicon Spice Inc." },

		{ 0x1400, "Artx", "Artx Inc." },
		{ 0x1401, "CR-Systems", "CR-Systems A/S" },
		{ 0x1402, "Meilhaus", "Meilhaus Eletronic GmbH" },
		{ 0x1403, "Ascor", "Ascor Inc." },
		{ 0x1404, "Fundamental", "Fundamental Software Inc." },
		{ 0x1405, "Excalibur", "Excalibur Systems Inc." },
		{ 0x1406, "OCE", "OCE' Printing Systems GmbH" },
		{ 0x1407, "Lava", "Lava Computer Mfg Inc." },
		{ 0x1408, "Aloka", "Aloka Company Ltd." },
		{ 0x1409, "Timedia", "Timedia Technology Company Ltd." },
		{ 0x140A, "DSP", "DSP Research Inc." },
		{ 0x140B, "Ramix", "Ramix Inc." },
		{ 0x140C, "Elmic", "Elmic Systems Inc." },
		{ 0x140D, "Matsushita", "Matsushita Electric Works Ltd." },
		{ 0x140E, "Goepel", "Goepel Electronic GmbH" },
		{ 0x140F, "Salient", "Salient Systems Corporation" },

		{ 0x1410, "Midas", "Midas Lab Inc." },
		{ 0x1411, "Ikos", "Ikos Systems Inc." },
		{ 0x1412, "Ensemble", "IC Ensemble Inc." },
		{ 0x1413, "Addonics", "Addonics" },
		{ 0x1414, "Microsoft", "Microsoft Corporation", "*" },
		{ 0x1415, "Oxford", "Oxford Semiconductor Ltd." },
		{ 0x1416, "Multiwave", "Multiwave Innovation Pte Ltd." },
		{ 0x1417, "Convergenet", "Convergenet Technologies Inc." },
		{ 0x1418, "Kyushu", "Kyushu Electronics Systems Inc." },
		{ 0x1419, "Excel", "Excel Switching Corporation" },
		{ 0x141A, "Apache", "Apache Micro Peripherals Inc." },
		{ 0x141B, "Zoom", "Zoom Telephonics Inc." },
		{ 0x141D, "Digitan", "Digitan Systems Inc." },
		{ 0x141E, "Fanuc", "Fanuc Ltd." },
		{ 0x141F, "Visiontech", "Visiontech Ltd." },

		{ 0x1420, "Psion" ,"Psion Dacom Plc." },
		{ 0x1421, "ADS Tech", "ADS Technologies Inc." },
		{ 0x1422, "Ygrec", "Ygrec Systems Company Ltd." },
		{ 0x1423, "Custom Tech", "Custom Technology Corporation" },
		{ 0x1424, "Videoserver", "Videoserver Connections" },
		{ 0x1425, "Asic", "Asic Designers Inc." },
		{ 0x1426, "Storage Tech", "Storage Technology Corporation" },
		{ 0x1427, "Better", "Better On-Line Solutions" },
		{ 0x1428, "EDEC", "EDEC Company Ltd." },
		{ 0x1429, "Unex", "Unex Technology Corporation" },
		{ 0x142A, "Kingmax", "Kingmax Technology Inc." },
		{ 0x142B, "Radiolan", "Radiolan" },
		{ 0x142C, "Minton", "Minton Optic Industry Company Ltd." },
		{ 0x142D, "Pix Steam", "Pix Stream Inc." },
		{ 0x142E, "Vitec", "Vitec Multimedia" },
		{ 0x142F, "Radicom", "Radicom Research Inc." },
	
		{ 0x1430, "ITT Aerospace", "ITT Aerospace/Communications Division" },
		{ 0x1431, "Gilat", "Gilat Satellite Networks" },
		{ 0x1432, "Edimax", "Edimax Computer Company" },
		{ 0x1433, "Eltec", "Eltec Elektronik GmbH" },
		{ 0x1435, "Real Time", "Real Time Devices US Inc." },
		{ 0x1436, "CIS Tech", "CIS Technology Inc." },
		{ 0x1437, "Nissin", "Nissin Inc. Company" },
		{ 0x1438, "Atmel", "Atmel-Dream" },
		{ 0x1439, "Outsource", "Outsource Engineering & Manufacturing Inc." },
		{ 0x143A, "Stargate", "Stargate Solutions Inc." },
		{ 0x143B, "Canon", "Canon Research Center" },
		{ 0x143C, "Amlogic", "Amlogic Inc." },
		{ 0x143D, "Tamarack", "Tamarack Microelectronics Inc." },
		{ 0x143E, "Jones", "Jones Futurex Inc." },
		{ 0x143F, "Lightwell", "Lightwell Company Ltd. - Zax Division" },

		{ 0x1440, "Algol", "Algol Corporation" },
		{ 0x1441, "Agie", "Agie Ltd." },
		{ 0x1442, "Phoenix", "Phoenix Contact GmbH & Company" },
		{ 0x1443, "Unibrain", "Unibrain S.A." },
		{ 0x1444, "TRW", "TRW" },
		{ 0x1445, "Logical", "Logical Do Ltd." },
		{ 0x1448, "Alesis", "Alesis Studio Electronics" },
		{ 0x1449, "TUT", "TUT Systems Inc." },
		{ 0x144A, "Adlink", "Adlink Technology" },
		{ 0x144B, "Loronix", "Loronix Information Systems Inc." },
		{ 0x144C, "Catalina", "Catalina Research Inc." },
		{ 0x144E, "Olitec", "Olitec" },
		{ 0x144F, "Askey" , "Askey Computer Corp." },

		{ 0x1450, "Nexus", "Nexus Systems Inc." },
		{ 0x1451, "SP3D", "SP3D Chip Design GmbH" },
		{ 0x1453, "Mycom", "Mycom Inc." },
		{ 0x1454, "Altiga", "Altiga Networks" },
		{ 0x1455, "Logic++", "Logic Plus Plus Inc." },
		{ 0x1456, "Advanced", "Advanced Hardware Architectures" },
		{ 0x1457, "Neura", "Neura Communications Inc." },
		{ 0x1458, "Giga-Byte", "Giga-Byte Technology" },
		{ 0x1459, "Dooin", "Dooin Electronics" },
		{ 0x145A, "Escalate", "Escalate Networks Inc." },
		{ 0x145B, "Praim", "Praim SRL" },
		{ 0x145C, "Cryptek", "Cryptek" },
		{ 0x145D, "Gallant", "Gallant Computer Inc." },
		{ 0x145E, "Aashima", "Aashima Technology B.V." },
		{ 0x145F, "Baldor", "Baldor Electric Company" },

		{ 0x1460, "Dynarc", "Dynarc Inc." },
		{ 0x1461, "Avermedia", "Avermedia Technologies Inc." },
		{ 0x1462, "Micro-Star", "Micro-Star International Company Ltd." },
		{ 0x1463, "Fast", "Fast Corporation" },
		{ 0x1464, "Interactive", "Interactive Circuits & Systems Ltd." },
		{ 0x1465, "GN", "GN Nettest Telecom Div." },
		{ 0x1466, "Designpro", "Designpro Inc." },
		{ 0x1467, "Digicom" ,"Digicom SPA" },
		{ 0x1468, "Ambit", "Ambit Microsystems Corp." },
		{ 0x1469, "Cleveland", "Cleveland Motion Controls" },
		{ 0x146A, "IFR", "IFR Ltd." },
		{ 0x146B, "Parascan", "Parascan Technologies Ltd." },
		{ 0x146C, "Ruby", "Ruby Tech Corp." },
		{ 0x146D, "Tachyon", "Tachyon Inc." },
		{ 0x146E, "Williams", "Williams Electronic Games Inc." },
		{ 0x146F, "MultiDimensional", "Multi Dimensional Consulting Inc." },

		{ 0x1470, "Bay", "Bay Networks" },
		{ 0x1471, "ITE", "Integrated Telecom Express Inc." },
		{ 0x1472, "Daikin", "Daikin Industries Ltd." },
		{ 0x1473, "Zapex", "Zapex Technologies Inc." },
		{ 0x1474, "Carson", "Doug Carson & Associates" },
		{ 0x1475, "Picazo", "Picazo Communications" },
		{ 0x1476, "Mortara", "Mortara Instrument Inc." },
		{ 0x1477, "Net Insight", "Net Insight" },
		{ 0x1478, "Diatrend", "Diatrend Corporation" },
		{ 0x1479, "Toray", "Toray Industries Inc." },
		{ 0x147A, "Formosa", "Formosa Industrial Computing" },
		{ 0x147B, "Abit", "Abit Computer Corp." },
		{ 0x147C, "Aware", "Aware Inc." },
		{ 0x147E, "Matsushita", "Matshushita Graphic Communication Systems Inc." },
		{ 0x147F, "Nihon", "Nihon Unisys Ltd." },
		
		// Everything here down has been checked for a URL on Yahoo
		{ 0x1480, "SCII", "SCII Telecom", "www.sciitelecom.com" },
		{ 0x1481, "Biopac", "Biopac Systems Inc.", "*" },
		{ 0x1482, "ISYTEC", "Integrierte Systemtechnik GmbH", "www.i2s.de" },
		{ 0x1483, "Labway", "Labway Corporation", "www.labway.com.tw" },
		{ 0x1484, "Logic", "Logic Corporation" },
		{ 0x1485, "ERMA", "ERMA Electronic GmbH" },
		{ 0x1486, "L3", "L3 Communications Telemetry & Instrumentation", "www.ti.l-3com.com" },
		{ 0x1487, "Marquette", "Marquette Medical Systems" },
		{ 0x1488, "Kontron", "Kontron Electronik GmbH" },
		{ 0x1489, "Kye", "Kye Systems Corporation", "www.geniusnet.com.tw" },
		{ 0x148A, "Opto22", "Opto 22", "*" },
		{ 0x148B, "InnoMediaLogic", "InnoMediaLogic Inc.", "www.iml-cti.com" },
		{ 0x148C, "CP Tech", "C.P. Technology Co. Ltd." },	
		{ 0x148D, "Digicom", "Digicom Systems Inc.", "www.digicomsys.com" },
		{ 0x148E, "OSI+", "OSI Plus Corporation" },
		{ 0x148F, "Planet", "Plant Equipment Inc.", "www.peinc.com" },
		
		{ 0x1490, "Stone", "Stone Microsystems Pty Ltd." },
		{ 0x1491, "Zeal", "Zeal Corporation" },
		{ 0x1492, "TimeLogic", "Time Logic Corporation" },
		{ 0x1493, "Maker", "Maker Communications", "*" },
		{ 0x1494, "Wintop", "Wintop Technology Inc.", "www.wintop.com.tw" },
		{ 0x1495, "Tokai", "Tokai Communications Industry Co. Ltd." },
		{ 0x1496, "Joytech", "Joytech Computer Co. Ltd.", "*" },
		{ 0x1497, "SMA", "SMA Regelsysteme GmbH", "www.sma.de" },
		{ 0x1498, "Tews", "Tews Datantechnik GmbH", "www.tews-datentechnik.com" },
		{ 0x1499, "Emtec", "Emtec Co. Ltd.", "www.emtech.co.jp" },
		{ 0x149A, "Andor-Tech", "Andor Technology Ltd.", "*" },
		{ 0x149B, "Seiko", "Seiko Instruments Inc.", "www.sii.co.jp" },
		{ 0x149C, "Ovislink", "Ovislink Corporation", "www.ovislink.com.tw" },
		{ 0x149D, "Newtek", "Newtek Inc.", "*" },
		{ 0x149E, "Mapletree", "Mapletree Networks Inc.", "www.mapletreenetworks.com" },
		{ 0x149F, "Lectron", "Lectron Co. Ltd.", "www.lectronic.com.tw" },
		
		{ 0x14A0, "Softing", "Softing GmbH" },
		{ 0x14A1, "Systembase", "Systembase Co. Ltd." },
		{ 0x14A2, "Millennium", "Millennium Engineering Inc." },
		{ 0x14A3, "Maverick", "Maverick Networks" },
		{ 0x14A4, "GVC", "GVC/BCM Advanced Research", "www.bcmcom.com" },
		{ 0x14A5, "Xionics", "Xionics Document Technologies Inc.", "*" },
		{ 0x14A6, "Innova", "Innova Computers GmbH & Co. KG" },
		{ 0x14A7, "Mythos", "Mythos Systems Inc." },
		{ 0x14A8, "Featron", "Featron Technologies Corporation" },
		{ 0x14A9, "Hivertec", "Hivertec Inc." },
		{ 0x14AA, "Advanced MOS", "Advanced MOS Technology Inc." },
		{ 0x14AC, "Novaweb", "Novaweb Technologies Inc.", "*" },
		{ 0x14AD, "Time Space", "Time Space Radio AB" },
		{ 0x14AE, "CTI", "CTI Inc." },
		{ 0x14AF, "Guillemot", "Guillemot Corporation", "*" },
		
		{ 0x14B0, "BST", "BST Communication Technology Ltd." },
		{ 0x14B1, "Nextcom", "Nextcom K.K.", "www.nextcom.co.jp" },
		{ 0x14B2, "Ennovate", "Ennovate Networks Inc.", "www.ennovatenetworks.com" },
		{ 0x14B3, "Xpeed", "Xpeed Inc.", "*" },
		{ 0x14B4, "Philips", "Philips Business Electronics B.V." },
		{ 0x14B5, "Creamware", "Creamware GmbH", "*" },
		{ 0x14B6, "Quantum", "Quantum Data Corporation" },
		{ 0x14B7, "Proxim", "Proxim Inc.", "*" },
		{ 0x14B8, "Techsoft", "Techsoft Technology Co. Ltd." },
		{ 0x14B9, "Aironet", "Aironet Wireless Communications Inc.", "*" },
		{ 0x14BA, "Internix", "Internix Inc." },
		{ 0x14BB, "Semtech", "Semtech Corporation", "*" },
		{ 0x14BD, "Cardio", "Cardio Control N.V." },
		{ 0x14BE, "L-3", "L-3 Communications Corporation", "www.L-3com.com" },
		{ 0x14BF, "Spider", "Spider Communications Inc." },
		
		{ 0x14C1, "Myricom", "Myricom Inc.", "www.myri.com" },
		{ 0x14C2, "DTK", "DTK Computer", "www.dtc.com.tw" },
		{ 0x14C5, "ABB", "ABB Automation Products AB", "www.abb.se" },
		{ 0x14C6, "DataRace", "Data Race Inc.", "*" },
		{ 0x14C7, "Modular", "Modular Technology Holdings Ltd." },
		{ 0x14C8, "Turbocomm", "Turbocomm Technology Inc." },
		{ 0x14C9, "Odin", "Odin Telesystems Inc.", "www.odints.com" },
		{ 0x14CA, "PE Logic", "PE Logic Corporation" },
		{ 0x14CB, "Billionton", "Billionton Systems Inc." },
		{ 0x14CC, "Nakayo", "Nakayo Telecommunications Inc.", "www.nyc.co.jp" },
		{ 0x14CD, "UniSci", "Universal Scientific Industries" },
		{ 0x14CE, "Whistle", "Whistle Communications", "*" },
		{ 0x14CF, "TekMicro", "Tek Microsystems Inc.", "*" },
		
		{ 0x14D1, "Hi-Tech", "Computer Hi-Tech Co. Ltd." },
		{ 0x14D2, "Titan", "Titan Electronics Inc." },
		{ 0x14D3, "Cirtech", "Cirtech UK Ltd." },
		{ 0x14D4, "Panacom", "Panacom Technology Corporation" },
		{ 0x14D5, "Nitsuko", "Nitsuko Corporation", "*" },
		{ 0x14D6, "Accusys", "Accusys Inc." },
		{ 0x14D7, "Hewtech", "Hirakawa Hewtech Corporation", "www.hewtech.co.jp" },
		{ 0x14D8, "hopf", "hopf Elektronik GmbH", "www.hopf-time.com" },
		{ 0x14D9, "Alpha", "Alpha Processor Inc." },
		{ 0x14D0, "Ericsson", "Ericsson Axe R&D", "*" },
		{ 0x14DA, "NAL", "National Aerospace Laboratories" },
		{ 0x14DB, "Avlab", "Avlab Technology Inc." },
		{ 0x14DC, "Amplicon", "Amplicon Liveline Ltd.", "www.amplicon.co.uk" },
		{ 0x14DD, "Boulder", "Boulder Design Labs Inc. "},
		{ 0x14DE, "Applied", "Applied Integration Corporation" },
		{ 0x14DF, "Basic", "Basic Communications Corporation "},

		{ 0x14E1, "Invertex", "Invertex", "*" },
		{ 0x14E2, "InfoLibria", "InfoLibria Inc.", "*" },
		{ 0x14E3, "Amtel", "Amtel Co." },
		{ 0x14E4, "Broadcom", "Broadcom Corporation", "*" },

		{ 0x1668, "Action Tec", "Action Tec Electronics Inc." },
		{ 0x1B13, "Jaton", "Jaton Corporation, USA", "*" },
/* */	{ 0x1C1C, "Symphony", "Symphony" } ,
/* */	{ 0x1DE1, "Tekram", "Tekram", "*" } ,

		{ 0x21C3, "21st Century" ,"21st Century Computer Corporation" },
		{ 0x270B, "Xantel", "Xantel Corporation", "*" },
/* */	{ 0x270F, "ChainTech", "ChainTech Computer Company Ltd.", "www.chaintech.com.tw" } ,

/* */	{ 0x3000, "Hansol", "Hansol Electronics Inc.", "www.hansolel.co.kr" } ,
/* */	{ 0x3142, "PostImpressions", "Post Impressions Systems" } ,
		{ 0x3388, "Hint", "Hint Corporation", "www.hintcorp.com" },
/* */	{ 0x3D3D, "3DLabs", "3DLabs Inc. Ltd.", "*" } ,

		{ 0x4005, "Avance", "Avance Logic Inc.", "www.realtek.com.tw" } ,
		{ 0x4444, "Internext", "Internext Compression Inc." },
/* */	{ 0x4594, "Cogetec", "Cogetec Informatique Inc.", "*" } ,
/* */	{ 0x4680, "UMAX", "UMAX Computer Corporation", "*" } ,
		{ 0x4843, "Hercules" ,"Hercules Computer Technology Inc.", "*" },
		{ 0x4942, "Creative", "Creative Labs Inc.", "*" }, // FAKE FOR SB128
		{ 0x4943, "Growth", "Growth Networks Inc.", "www.growthnetworks.com" },
		{ 0x4978, "Axil", "Axil Computer Inc." },
/* */	{ 0x4B10, "Buslogic", "Buslogic Inc./Mylex Corporation", "*" } ,
		{ 0x4C48, "Lung", "Lung Hwa Electronics" },
		{ 0x4D51, "MediaQ", "MediaQ Inc." },
		{ 0x4DDC, "ILC Data", "ILC Data Device Corporation", "www.ilcddc.com" },

		{ 0x5053, "Voyetra", "Voyetra Technologies", "*" },
		{ 0x5134, "Qualcomm", "Qualcomm Inc.", "*" },
		{ 0x5333, "S3", "S3 Inc.", "*" } ,
		{ 0x544C, "Teralogic", "Teralogic Inc.", "www.teralogic-inc.com" },
/* */ 	{ 0x5455, "TU-Berlin", "Technische Universtiaet Berlin" } ,
		{ 0x5555, "Genroco", "Genroco Inc.", "*" },
/* */	{ 0x5519, "Cnet", "Cnet Technologies Inc." } ,
/* */	{ 0x5700, "NeTpower", "NeTpower Inc.", "*" } ,

/* */	{ 0x6374, "C4T", "c't Magazin fr Computertechnik", "www.ct.nl" } ,
		{ 0x6409, "Logitec", "Logitec Corporation", "*" },
		{ 0x6666, "Decision", "Decision Computer International" },

		{ 0x7604, "ONE", "O.N. Electronic Co. Ltd." },

/* */	{ 0x8008, "Quancom", "Quancom Electronic GmbH", "www.quancom.de" } , // Unsure
		{ 0x8086, "Intel", "Intel Corporation", "*" } ,
/* */	{ 0x8800, "Trigem", "Trigem Computer", "*" } ,
		{ 0x8866, "T-Square", "T-Square Design Inc." },
/* */	{ 0x8888, "SiMagic", "Silicon Magic", "*" } ,
		{ 0x8E0E, "Computone", "Computone Corporation", "*" } ,

		{ 0x9004, "Adaptec", "Adaptec Inc.", "*" } ,
		{ 0x9005, "Adaptec", "Adaptec Inc.", "*" } ,		
/* */	{ 0x907F, "ATronics", "ATronics International Inc.", "*" } ,

		{ 0xA0A0, "AOpen", "AOpen Inc.", "*" },
		{ 0xA0F1, "Unisys", "Unisys Corporation", "*" },
		{ 0xA200, "NEC", "NEC Corporation", "*" },
		{ 0xA259, "HP", "Hewlett Packard", "*" },
		{ 0xA25B, "HP", "Hewlett Packard GmbH", "*" },
		{ 0xA304, "Sony", "Sony Corporation", "*" },
		{ 0xA727, "3Com", "3Com Corporation", "*" },
		{ 0xAA42, "Scitex", "Scitex Digital Video", "www.scitexdv.com" },

		{ 0xB1B3, "Shiva", "Shiva Europe Ltd.", "*" },

		{ 0xC001, "TSI Telsys", "TSI Telsys" },
		{ 0xC0A9, "Crucial", "Micron/Crucial Technology", "*" },
		{ 0xC0DE, "Motorola", "Motorola", "www.mot.com" },
		{ 0xC0FE, "MotionEng", "Motion Engineering Inc.", "*" } ,
		{ 0xCAFE, "Chrysalis-its", "Chrysalis-Its Inc.", "*" },
		{ 0xCCCC, "Catapult", "Catapult Communications", "*" },

		{ 0xD4D4, "DY4", "DY 4 Systems Inc.", "*" } ,

		{ 0xE159, "TigerJet", "Tiger Jet Network Inc.", "*" } ,
		{ 0xECC0, "Echo", "Echo Corporation", "www.echospeech.com" },
		{ 0xEDD8, "ARK", "ARK Logic Inc.", "www.arklogic.com" } ,

		{ 0xFEDA, "Epigram", "Epigram Inc." },
		{ 0xFFFF, "INVALID", "INVALID VENDOR ID" } ,
};